title: "Christian Vonderstein"
remote_theme: pmarsceill/just-the-docs
color_scheme: nil

# Search settings
search_enabled: true
search.heading_level: 6
search.previews: 10
search.rel_url: true
search.button: true

# Footer config
footer_content: "Copyright &copy; 2022 Christian Vonderstein."
# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Display "back to top" button
back_to_top: true
back_to_top_text: "Back to top"

# Open Aux links in new tabs
aux_links_new_tab: true

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
