title: "Christian Vonderstein"
remote_theme: just-the-docs/just-the-docs
#theme: "just-the-docs"
color_scheme: nil
description: >- # this means to ignore newlines until "baseurl:"
  Christian Vonderstein's Personal Website.
  Contains information about my projects and other stuff.

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://vonderste.in" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cvonderstein
github_username:  cvonderstein

# Search settings
search_enabled: true
search.heading_level: 6
search.previews: 10
search.rel_url: true
search.button: true

# Footer config
footer_content: "Copyright &copy; 2022 Christian Vonderstein."
# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Display "back to top" button
back_to_top: true
back_to_top_text: "Back to top"

# Open Aux links in new tabs
aux_links_new_tab: true

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Include .well-known files for Matrix delegation
include: [".well-known"]

compress_html:
  ignore:
    envs: all
